os:
  - linux
  - osx
language: go
go:
  - 1.8
addons:
  apt:
    packages:
      - oracle-java8-set-default
env:
  - GAUGE_ROOT="/tmp/gauge"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi
script:
  - go run build/make.go
  - go test ./...
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> skel/gauge.properties
  - go run build/make.go --install --prefix=$GAUGE_ROOT
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - $GAUGE_ROOT/bin/gauge --install-all
  - java -version
  - echo $JAVA_HOME
  - TAGS="!unimplemented" ./starttests.sh java
